---
os: linux
dist: xenial
language: python

cache:
  pip: true

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry

install:
  - poetry install -E test -E docs

script:
  - poetry run pytest --cov=adopy
  - poetry run codecov

after_success:
  - poetry run flake8 adopy --format=pylint --statistics --exit-zero
  - poetry run pylint adopy --rcfile=setup.cfg --exit-zero

before_deploy:
  - poetry build

deploy:
  provider: releases
  token: $GH_TOKEN
  file_glob: true
  file: dist/**/*
  draft: true
  on:
    tags: true
